speech: manager.o speechManager.o
	g++ -g manager.o speechManager.o -o speech

speechManager.o: speechManager.cpp

manager.o: manager.cpp

.Phony: clean

clean:
	rm manager.o speechManager.o speech


